### ISSUE TITLE
Does PagedArray play well with SwiftlyJSON?

### ISSUE THREAD

**Issue by acegreen** [MrAlek/PagedArray#10]
Hello

Just wondering if this library plays well with JSON data Object. If so, how'd you go about linking them together? 

if it?
pagedArray.setElements(JSONobject.arrayobject, pageIndex: 1)

**Comment by MrAlek** [comment]
I would create real model objects from the JSON array before putting them in the `PagedArray` but otherwise it should work :)

**Comment by acegreen** [comment]
What do you mean real model objects?

**Comment by MrAlek** [comment]
Let's say you're fetching users, instead of using plain JSON objects you could have a `User` class or struct that you create from a JSON dictionary. But for this library, you can use plain JSON objects as well, no problem.
