### ISSUE TITLE
How to deal with unknown data count

### ISSUE THREAD

**Issue by nonameplum** [MrAlek/PagedArray#14]
Hi,

Could you provide some example how to deal with API data is not providing count of all data?
For now it looks that everything is based on known count.

**Comment by rlam3** [comment]
I'm looking for the same solution. @nonameplum were you able to figure this out?

**Comment by nonameplum** [comment]
@rlam3 I had to create my on Array class that supports unknown count and also Pagination Manager that cooperates with it.

**Comment by MrAlek** [comment]
The purpose of this library is to provide a paging data structure where the total count is known for a scrolling fixed-count UI. If you want to implement something like a news feed with an indefinite count of data, this data structure is not for you.
