### ISSUE TITLE
In comparison to using Realm. What are some tradeoffs and benefits of using this paging system?

### ISSUE THREAD

**Issue by rlam3** [MrAlek/PagedArray#15]
In comparison to using Realm. What are some tradeoffs and benefits of using this paging system?

https://realm.io/

**Comment by MrAlek** [comment]
Realm is a database for persisting data whilst `PagedArray` is only for in memory allocation of data, built purposefully for table views and collection views where you want a smooth scrolling experience even though your backend API is paging.
