### ISSUE TITLE
Migrate to Swift 2.3 and Swift 3

### ISSUE THREAD

**Issue by suchtomwow** [MrAlek/PagedArray#17]
In order to migrate and test our app to Swift 2.3/3.0 prior to the release of Xcode 8 and iOS 10, all of our dependencies need to be migrated first.

This can be solved by pointing our podfile to those respective Swift 2.3/3.0 branches, but this repo does not appear to have either of those branches.

[This blog post](http://www.jessesquires.com/migrating-to-swift-3/) contains helpful tips for migrating open source libraries.

**Comment by MrAlek** [comment]
Hey! Thanks for reminding me, getting this done as soon as possible.

**Comment by MrAlek** [comment]
Swift 2.3 is now up! Working on 3.0 but that wasn't exactly trivial so will take a while.

**Comment by suchtomwow** [comment]
Thanks for the quick response!

**Comment by MrAlek** [comment]
And now [3.0](https://github.com/MrAlek/PagedArray/tree/swift3.0) is done too :) Really happy with some of the renamings but of course they will break some existing code. Should be easy to migrate though. Thanks @suchtomwow for giving me the push to do it :)
