### ISSUE TITLE
Changes in the dataset

### ISSUE THREAD

**Issue by Alex293** [MrAlek/PagedArray#18]
How can I handle the changes in the dataset ? I think this should work only if the data is not ordered or i'm i wrong ? If an ID is missing and added while you scroll you will have a shift in the rows

**Comment by MrAlek** [comment]
The purpose of this library is just to be a data structure and nothing more. There are several strategies to what you could do when data changes depending on how the API your working against looks like. Easiest thing is just to rebuild the data structure from scratch and start reloading the other pages that might also have changed. Hope that helps :)
