### ISSUE TITLE
Connecting with the API responses

### ISSUE THREAD

**Issue by mrfarukturgut** [MrAlek/PagedArray#21]
Hi, I am curious about the proper of connecting this library with the responses of my API. To be more clear, Our API sends back the data page by page which means I have to make a HTTP request for each page. I am looking for a library that could ease my job here, so do you think that I can use this repository? If yes, how? (the efficient way). Thanks

**Comment by MrAlek** [comment]
Hi, sorry for never getting back to you. Paginated APIs where you make a request for each page is exactly what `PagedArray` is created for, as long as you get to know the total count from the API. I'm closing this issue but feel free to re-open in case you have any current questions about how to use the data structure.
